{% set name = "graphblas-algorithms" %}
{% set version = "2022.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphblas-algorithms-{{ version }}.tar.gz
  sha256: 3091bcb4b4b7705a244b5a73537d9bec377c791117e9c5f04ae9cb60d27c585b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - python-graphblas >=2022.11.0

test:
  imports:
    - graphblas_algorithms
  commands:
    - pip check
    - pytest -v --pyargs graphblas_algorithms
  requires:
    - pip
    - pytest
    - networkx

about:
  home: https://github.com/python-graphblas/graphblas-algorithms
  summary: Fast graph algorithms written in GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Fast graph algorithms written in Python with `python-graphblas` targeting the
    NetworkX API and may be used as a backend to NetworkX 3.0 via dispatching.
  dev_url: https://github.com/python-graphblas/graphblas-algorithms

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
