{% set name = "graphblas-algorithms" %}
{% set version = "2023.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphblas-algorithms-{{ version }}.tar.gz
  sha256: 1f9eafd0d4e080d9f6e19f5b84b491409cb7581973f5f9718fa168ef0544f20b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - python-graphblas >=2023.1.0

test:
  imports:
    - graphblas_algorithms
  commands:
    - pip check
    # - pytest -v --pyargs graphblas_algorithms
  requires:
    - pip
    # - pytest
    # - networkx >=3.0

about:
  home: https://github.com/python-graphblas/graphblas-algorithms
  summary: Fast graph algorithms written in GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Fast graph algorithms written in Python with `python-graphblas` targeting the
    NetworkX API and may be used as a backend to NetworkX 3.0 via dispatching.
  dev_url: https://github.com/python-graphblas/graphblas-algorithms

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
